version: 0.2
phases:
  install:
    commands:
      - echo "Installing kubectl and helm..."
      # Install kubectl using package manager (most reliable)
      - curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
      - echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list
      - apt-get update
      - apt-get install -y kubectl
      
      # Install helm
      - curl https://baltocdn.com/helm/signing.asc | apt-key add -
      - echo "deb https://baltocdn.com/helm/stable/debian/ all main" | tee /etc/apt/sources.list.d/helm-stable-debian.list
      - apt-get update
      - apt-get install -y helm
      
      # Verify installations
      - kubectl version --client --short
      - helm version --short
  pre_build:
    commands:
      - echo "Updating kubeconfig for cluster ${CLUSTER_NAME}"
      - aws eks update-kubeconfig --region $REGION --name $CLUSTER_NAME
      - echo "Verifying cluster access..."
      - kubectl get nodes
  build:
    commands:
      - echo "Adding EKS Helm repository..."
      - helm repo add eks https://aws.github.io/eks-charts
      - helm repo update
      - echo "Installing AWS Load Balancer Controller..."
      - |
        helm upgrade --install aws-load-balancer-controller \
          eks/aws-load-balancer-controller \
          -n aws-load-balancer-controller \
          --create-namespace \
          --set clusterName=$CLUSTER_NAME \
          --set serviceAccount.create=true \
          --set serviceAccount.name=aws-load-balancer-controller \
          --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"=$ALB_CONTROLLER_ROLE_ARN \
          --set region=$REGION \
          --set vpcId=$VPC_ID \
          --set image.repository=602401143452.dkr.ecr.$REGION.amazonaws.com/amazon/aws-load-balancer-controller \
          --wait
  post_build:
    commands:
      - echo "Verifying ALB Controller installation..."
      - kubectl get deployment -n aws-load-balancer-controller aws-load-balancer-controller
      - echo "Checking ALB Controller pods..."
      - kubectl get pods -n aws-load-balancer-controller
      - echo "ALB Controller installed successfully!"
