version: '3'
services:
  frontend:
    build:
      context: ./FrontEnd
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./BackEnd
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
