version: '3'
services:
  frontend:
    build:
      context: ./FrontEnd
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./BackEnd
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/counterdb
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
