name: CI Pipeline
env:
  DEFAULT_REGION: us-east-1
  FRONTEND_ECR_REPO: frontend-app
  BACKEND_ECR_REPO: backend-app

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  setup-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
      - name: Test
        run: |
          echo "AWS Region: ${{ env.AWS_REGION }}"
          echo "AWS Access Key ID (first 4 chars): ${AWS_ACCESS_KEY_ID:0:4}"
          echo "AWS Secret Access Key (first 4 chars): ${AWS_SECRET_ACCESS_KEY:0:4}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
      - name: "Configure AWS Credentials" 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
