name: CI Pipeline
env:
  DEFAULT_REGION: us-east-1
  FRONTEND_ECR_REPO: frontend-app
  BACKEND_ECR_REPO: backend-app
  AWS_REGION: us-east-1  # Explicitly define AWS_REGION

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  setup-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
      
      - name: Validate Secrets
        run: |
          if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
            echo "Error: AWS credentials are not set"
            exit 1
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Verify AWS Configuration
        run: |
          echo "AWS Region: $AWS_REGION"
          aws sts get-caller-identity
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
