name: CI Pipeline
on:
  push:
    branches: [master]
    paths:
      - "FrontEnd/**"
      - "BackEnd/**"
  pull_request:
    branches: [master]
    paths:
      - "FrontEnd/**"
      - "BackEnd/**"

jobs:
  setup-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Check for Frontend changes
        id: frontend-changes
        run: |
          echo "Frontend changes detected: $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'FrontEnd/' | wc -l)"
          echo "has_changes=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'FrontEnd/' | wc -l)" >> $GITHUB_OUTPUT

      - name: Check for Backend changes
        id: backend-changes
        run: |
          echo "Backend changes detected: $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'BackEnd/' | wc -l)"
          echo "has_changes=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'BackEnd/' | wc -l)" >> $GITHUB_OUTPUT

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}

      - name: Create Frontend ECR Repository
        env:
          FRONTEND_ECR_REPO: ${{ vars.FRONTEND_ECR_REPO }}
        run: |
          aws ecr describe-repositories --repository-names ${{ env.FRONTEND_ECR_REPO }} || \
          aws ecr create-repository --repository-name ${{ env.FRONTEND_ECR_REPO }}

      - name: Create Backend ECR Repository
        env:
          BACKEND_ECR_REPO: ${{ vars.BACKEND_ECR_REPO }}
        run: |
          aws ecr describe-repositories --repository-names ${{ env.BACKEND_ECR_REPO }} || \
          aws ecr create-repository --repository-name ${{ env.BACKEND_ECR_REPO }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push FrontEnd image
        if: steps.frontend-changes.outputs.has_changes != '0'
        uses: docker/build-push-action@v6.13.0
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          FRONTEND_ECR_REPO: ${{ vars.FRONTEND_ECR_REPO }}
        with:
          context: ./FrontEnd
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/${{ env.FRONTEND_ECR_REPO }}:latest
            ${{ env.ECR_REGISTRY }}/${{ env.FRONTEND_ECR_REPO }}:${{ env.IMAGE_TAG }}

      - name: Build and push BackEnd image
        if: steps.backend-changes.outputs.has_changes != '0'
        uses: docker/build-push-action@v6.13.0
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          BACKEND_ECR_REPO: ${{ vars.BACKEND_ECR_REPO }}
        with:
          context: ./BackEnd
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/${{ env.BACKEND_ECR_REPO }}:latest
            ${{ env.ECR_REGISTRY }}/${{ env.BACKEND_ECR_REPO }}:${{ env.IMAGE_TAG }}
