name: CI Pipeline
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  setup-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Validate Secrets
        run: |
          echo "region: ${{ vars.AWS_REGION }}"
          echo "region: ${{ vars.FRONTEND_ECR_REPO }}"
          echo "region: ${{ vars.BACKEND_ECR_REPO }}"
          echo "region: ${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "region: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
