name: CI Pipeline
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  setup-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Validate Secrets
        run: |
          echo "region: ${{ vars.AWS_REGION }}"
          echo "frontEnd: ${{ vars.FRONTEND_ECR_REPO }}"
          echo "BackEnd: ${{ vars.BACKEND_ECR_REPO }}"
          echo "Access Key ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "Access Key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          FRONTEND_ECR_REPO: ${{ vars.FRONTEND_ECR_REPO }}
          BACKEND_ECR_REPO: ${{ vars.BACKEND_ECR_REPO }}
